import {fireEvent,render,screen,within} from "@testing-library/react";
import {expect,it,vi} from "vitest";
vi.mock("next/navigation",()=>({useRouter:()=>({refresh:vi.fn()})}));
vi.mock("@/actions/wedding-cakes",()=>({saveCakeHouseholdAction:vi.fn(),dissolveCakeHouseholdAction:vi.fn()}));
import {WeddingCakeBoard} from "./wedding-cake-board";
import type {WeddingCakeData} from "@/lib/wedding-cakes";
const data:WeddingCakeData={workspace:{id:"w",name:"婚宴"},households:[{id:"h",name:"甲家",boxes:1,version:0}],guests:[{id:"a",name:"甲",version:0,seniority:"PEER",attendanceStatus:"ATTENDING",partySize:4,checkedIn:false,side:"PARTNER_A",relationshipLabel:"表姊",cakeHouseholdId:"h"},{id:"b",name:"乙",version:0,seniority:"PEER",attendanceStatus:"ATTENDING",partySize:1,checkedIn:false,side:"PARTNER_A",relationshipLabel:"表姊夫",cakeHouseholdId:"h"},{id:"c",name:"丙",version:0,seniority:"PEER",attendanceStatus:"DECLINED",partySize:1,checkedIn:false,side:"PARTNER_A",relationshipLabel:null,cakeHouseholdId:null}]};
it("previews one box per household and provides an export",()=>{render(<WeddingCakeBoard workspaceId="w" data={data}/>);const region=screen.getByRole("region",{name:"發餅匯出預覽"});expect(within(region).getByText("乙、甲")).toBeInTheDocument();expect(within(region).getByText("乙：新郎的表姊夫；甲：新郎的表姊")).toBeInTheDocument();expect(within(region).queryByText("丙")).not.toBeInTheDocument();expect(screen.getByRole("link",{name:"匯出發餅名單（CSV）"})).toHaveAttribute("href",expect.stringContaining("/workspaces/w/guests/cakes/export"));});
it("edits existing household membership and preserves selected guests while searching",()=>{render(<WeddingCakeBoard workspaceId="w" data={data}/>);fireEvent.click(screen.getByRole("button",{name:"編輯家庭 甲家"}));expect(screen.getByLabelText("家庭名稱")).toHaveValue("甲家");expect(screen.getByLabelText("喜餅盒數")).toHaveValue(1);fireEvent.change(screen.getByLabelText("搜尋成員"),{target:{value:"丙"}});expect(screen.getByText("同一家人的成員（已選 2 筆）")).toBeInTheDocument();expect(screen.getAllByRole("checkbox")).toHaveLength(1);});
